### PR TITLE
Adds Google Analytics and firebase

### PR DESCRIPTION
**Pull request by tn-tran**

### CODE REVIEW

**Comment by tn-tran** [comment]
Examples of events logged
Screenshot 2023-06-14 at 9 21 24 PM

**Review by manish-andankar — CHANGES_REQUESTED** [review]
Please Exclude ReadMe file, and raise the PR again.

**Review by manish-andankar — COMMENTED** [review]
Please raise another PR without ReadMe file. This PR will be closed.

**Comment by manish-andankar** [comment]
Please raise another PR excluding the ReadMe file.

**Pull request closed without merging**
